services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"   # only necessary if you want to acccess Postgres from outside of Docker
    environment:
      POSTGRES_PASSWORD: un1c0rn
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d  # points to directory with init scripts

    